### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by fengguowudi** [gG8Fkpxq/BingLocalhost#4]
report:
Traceback (most recent call last):
  File "/root/BingLocalhost/main.py", line 11, in <module>
    from utils import postprocess
  File "/root/BingLocalhost/utils.py", line 16, in <module>
    self, y: List[Tuple[str | None, str | None]]

运行环境：
Debian11 64x 英国 6.3.0Linux内核

Python 3.9

使用了if-elif-else

**Comment by BlackSharkJ** [comment]
只有这些报错信息吗？报错信息看起来不完整。目前看起来像是`from typing import List, Tuple`的错误，试试把
```python
def postprocess(
    self, y: List[Tuple[str | None, str | None]]
) -> List[Tuple[str | None, str | None]]:
```
改为
```python
def postprocess(self, y):
```

**Comment by fengguowudi** [comment]
是否支援Linux ？

**Comment by BlackSharkJ** [comment]
> 是否支援Linux ？

理论上，只要可以使用Python3就可以使用。目前我只知道你报错误的地方，但是不知道具体的报错提示是什么？

**Comment by fengguowudi** [comment]
Traceback (most recent call last):
  File "/root/BingLocalhost/main.py", line 14, in <module>
    cookieList = [_ for _ in Path(cookiePath).iterdir()]
  File "/root/BingLocalhost/main.py", line 14, in <listcomp>
    cookieList = [_ for _ in Path(cookiePath).iterdir()]
  File "/usr/lib/python3.9/pathlib.py", line 1149, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'root/cookie.json'

**Comment by fengguowudi** [comment]
> > 是否支援Linux ？
> 
> 理论上，只要可以使用Python3就可以使用。目前我只知道你报错误的地方，但是不知道具体的报错提示是什么？

按照您的提示修改之后，已经可以运行，但是无法调用cookie，目前

**Comment by fengguowudi** [comment]
Traceback (most recent call last):
  File "/root/BingLocalhost/main.py", line 14, in <module>
    cookieList = [_ for _ in Path(cookiePath).iterdir()]
  File "/root/BingLocalhost/main.py", line 14, in <listcomp>
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/BingLocalhost/main.py", line 122, in change_style
    cookieDict[IP] = [Chatbot(random.choice(cookieList)), None]
  File "/usr/local/lib/python3.9/dist-packages/EdgeGPT.py", line 363, in __init__
    _Conversation(self.cookies, self.proxy),
  File "/usr/local/lib/python3.9/dist-packages/EdgeGPT.py", line 236, in __init__
    for cookie in cookies:
TypeError: 'PosixPath' object is not iterable

**Comment by BlackSharkJ** [comment]
> > > 是否支援Linux ？
> > 
> > 
> > 理论上，只要可以使用Python3就可以使用。目前我只知道你报错误的地方，但是不知道具体的报错提示是什么？
> 
> 按照您的提示修改之后，已经可以运行，但是无法调用cookie，目前

如果您有多个cookie，可以把cookie文件单独放到一个文件夹中（请确保这个文件夹只有储存cookie的json文件），然后把目录赋值给`main.py`中的
```python
cookiePath = r"./cookiePath"  # 填写存放Bing的cookies目录
```
这样会方便您管理您的cookies，如果您只有一个cookie并且不想因此单独创建一个目录用于保存cookie文件，可以把保存cookie的json路径通过列表嵌套后赋值给`main.py`中的`cookieList`，如
```
cookieList = [r"c:/your_cookie.json"]
```

**Comment by fengguowudi** [comment]
https://cloud.hoox.cf/ 无法使用

**Comment by BlackSharkJ** [comment]
> https://cloud.hoox.cf/ 无法使用

可以描述一下具体的行为吗？然后把后台的报错信息提供给我，今天比较晚了，我可能需要明天才能帮您继续解决问题

**Comment by fengguowudi** [comment]
> > https://cloud.hoox.cf/ 无法使用
> 
> 可以描述一下具体的行为吗？然后把后台的报错信息提供给我，今天比较晚了，我可能需要明天才能帮您继续解决问题


问题就是没报错。。。没事，您先睡吧

**Comment by fengguowudi** [comment]
所以我该怎么做

**Comment by BlackSharkJ** [comment]
> 所以我该怎么做

我还不知道您的具体是什么问题，我进入您提供的网站点击没有反应，无法判断是哪里出了错。您有尝试过在本地使用吗？

**Comment by fengguowudi** [comment]
> > 所以我该怎么做
> 
> 我还不知道您的具体是什么问题，我进入您提供的网站点击没有反应，无法判断是哪里出了错。您有尝试过在本地使用吗？

本地无Linux环境，无法控制变量，或者该程序有无debug模式之类的，我看看日志

**Comment by BlackSharkJ** [comment]
该程序无debug模式，您可以尝试自行修改一下，我实在是没有弄明白您描述的到底是什么问题，抱歉。
